"""
Django settings for loan_management project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!@md(30o^(5!@hbwdq8fu42-l)&$&bqq@7w6-@%qsy-fxe00hq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

ADMIN_SITE_HEADER = "Loan Management Admin"
ADMIN_SITE_TITLE = "Loan Admin"
ADMIN_INDEX_TITLE = "Welcome to the Loan Management Dashboard"

# Application definition

INSTALLED_APPS = [
    # 'jazzmin',
    "django_static_fontawesome",
    "django_static_jquery3",
    "django_admin_global_sidebar",
    # 'members',  # moved before django.contrib.admin to override admin templates
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'import_export',
    "rangefilter",
    
    'crispy_forms',   # recommended for nice forms in reports
    'crispy_bootstrap5',
     'loans.apps.LoansConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'loan_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'loan_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'loan_management',
#         'USER': 'loan_user',
#         'PASSWORD': 'Humility@1995',
#         'HOST': 'localhost',   # Django and Postgres are on the same VPS
#         'PORT': '5432',
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Use custom user model
AUTH_USER_MODEL = 'loans.CustomUser'

JAZZMIN_SETTINGS = {
    "site_title": "Loan Management Admin",
    "site_header": "Loan Management",
    "welcome_sign": "Welcome to Loan Management Dashboard",
    "show_sidebar": True,  # 👈 ensures sidebar shows
    "navigation_expanded": True,  # sidebar expanded by default

    # Example custom menu
    "custom_links": {
        "members": [{
            "name": "Add New Borrower",
            "url": "admin:app_borrower_add",
            "icon": "fas fa-user-plus",
        }],
    },

    # You can also reorder apps/models if you want
    # "order_with_respect_to": ["members", "loans", "applications"],
}

DJANGO_ADMIN_GLOBAL_SIDEBAR_MENUS = [
    {
        "title": "Dashboard",
        "icon": "fas fa-home",
        "url": "/custom_admin/loans/",
    },
    {
        "title": "Loan Management",
        "icon": "fas fa-money-bill-wave",
        "children": [
            {"title": "Lenders", "url": "/custom_admin/loans/lender/"},
            {"title": "Borrowers", "url": "/custom_admin/loans/borrower/"},
            {"title": "Loan Applications", "url": "/custom_admin/loans/loanapplication/"},
            {"title": "Loans", "url": "/custom_admin/loans/loan/"},
            {"title": "Loan Repayments", "url": "/custom_admin/loans/loanrepayment/"},
            {"title": "Repayment Schedules", "url": "/custom_admin/loans/repaymentschedule/"},
            {"title": "Collateral", "url": "/custom_admin/loans/collateral/"},
            {"title": "Loan Products", "url": "/custom_admin/loans/loanproduct/"},
        ]
    },
    {
        "title": "Operations",
        "icon": "fas fa-cogs",
        "children": [
            {"title": "Staff", "url": "/custom_admin/loans/staff/"},
            {"title": "Users", "url": "/custom_admin/loans/customuser/"},
            {"title": "Operating Expenses", "url": "/custom_admin/loans/operatingexpense/"},
        ]
    },
    {
        "title": "Bank & Cash",
        "icon": "fas fa-university",
        "children": [
            {"title": "Bank Accounts", "url": "/custom_admin/loans/bankaccount/"},
            {"title": "Bank Transactions", "url": "/custom_admin/loans/banktransaction/"},
            {"title": "Cash Transactions", "url": "/custom_admin/loans/cashtransaction/"},
        ]
    },
    {
        "title": "Portfolio",
        "icon": "fas fa-chart-line",
        "children": [
            {"title": "Portfolio Overview", "url": "/custom_admin/loans/loanportfolio/"},
        ]
    },
    {
        "title": "Reports",
        "icon": "fas fa-file-alt",
        "children": [
            {
                "title": "Portfolio Overview",
                "url": "/custom_admin/loans/loanportfolio/"
            },
            {
                "title": "Loan Performance Report",
                "url": "/custom_admin/loans/reports/loan-performance/"
            },
        ]
    }
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
