# Generated by Django 5.2.6 on 2025-10-31 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lender',
            options={},
        ),
    ]
